### ISSUE TITLE
Gift aid add on for UK based donations

### ISSUE THREAD

**Issue by maderesponsively** [cferdinandi/gmt-donations#19]
_Gift Aid is a UK tax incentive that enables tax-effective giving by individuals to charities in the United Kingdom._

It would be great to add a check box to allow donators to tell the charities using gmt-donations that they pay UK taxes.  I.e. "I am a UK tax payer and would like X to reclaim tax on all donations I make from today onwards."

For more information about the rules on this:
https://www.gov.uk/guidance/gift-aid-declarations-claiming-tax-back-on-donations

**Comment by cferdinandi** [comment]
Hi, happy to add this to a future release. Just to clarify (as the site you linked to probably assumes I'm in the UK and know what this is all about): the UK taxes you (the nonprofit) on donations unless the donor states (in writing) that they pay UK taxes and want you to get that tax money you would otherwise pay back? Or am I missing something?

**Comment by maderesponsively** [comment]
Yes, Donations from non-UK taxpayers are not eligible for Gift Aid. 

Under HMRC’s Gift Aid scheme, charities can reclaim an amount equal to basic rate tax (20%) on the amount of the donation, plus basic rate tax already paid by that taxpayer on that donation. To do this, you need to use a ‘grossing up’ fraction.

Let's take a £100 donation as an example.

The fraction applied to calculate Gift Aid is 100 x 20/80. This is 25% of £100 which equals £25.

_Might need to think about the following...._
HMRC regulations also mean that we can’t reclaim Gift Aid on a donation if the donor told us that:
- the donation was on behalf of someone else or a group of people
- the donation was on behalf of a company
- the donation was to a family member or friend doing an event where the charity is contributing to their costs
- the donation was made in return for goods, rights or services.

**Comment by cferdinandi** [comment]
This plugin has been deprecated and will no longer be maintained or updated.
