### ISSUE TITLE
Recurring Payments redirect to wp-admin

### ISSUE THREAD

**Issue by darrenipim** [cferdinandi/gmt-donations#39]
Hi

Are there any known issues with recurring payments for both Stripe and PayPal?

Whenever we try to put a recurring payment through in test mode, the page redirects to the wp-admin and the donation or donor details are not saved. When we go back to the page containing the form, there's a message 'We were unable to process your donation. Please try again.'

Thanks

**Comment by cferdinandi** [comment]
Hi, sorry for the delayed response. I have no seen that issue before, and unfortunately, I'm unable to offer support for this plugin at this time.
